server:
  port: 80

spring:
  application:
    name: odd-server
  datasource:
    url: jdbc:mysql://${DB_HOST:123.56.83.2}:${DB_PORT:3306}/auth?&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver


response:
  result:
    code: 200
    msg: ??

logging:
  file:
    path: /app/log/
    name: ${spring.application.name}