server:
  port: 80

spring:
  application:
    name: odd-server
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/auth?&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      open-in-view: true
      hibernate:
        ddl-auto: none
#  flyway:
#    enabled: true
#    locations: classpath:/db/migration

response:
  result:
    code: 200
    msg: ??